import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

/**
 * Export a DOM element as PDF using jsPDF + html2canvas
 * @param elementId - The ID of the HTML element to capture
 * @param filename - PDF filename (without .pdf extension)
 */
export const exportElementAsPDF = async (
  elementId: string,
  filename = 'weathercast-export',
): Promise<void> => {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element with ID "${elementId}" not found`)
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#0a0f1e',
    scale: 2,
    useCORS: true,
    allowTaint: false,
    logging: false,
  })

  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF({
    orientation: canvas.width > canvas.height ? 'landscape' : 'portrait',
    unit: 'px',
    format: [canvas.width, canvas.height],
  })

  pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height)
  pdf.save(`${filename}.pdf`)
}

/**
 * Export a DOM element as PNG image download
 */
export const exportElementAsPNG = async (
  elementId: string,
  filename = 'weathercast-export',
): Promise<void> => {
  const element = document.getElementById(elementId)
  if (!element) throw new Error(`Element #${elementId} not found`)

  const canvas = await html2canvas(element, {
    backgroundColor: '#0a0f1e',
    scale: 2,
    useCORS: true,
    logging: false,
  })

  const link = document.createElement('a')
  link.download = `${filename}.png`
  link.href = canvas.toDataURL()
  link.click()
}

/**
 * Generate a weather report PDF with custom content
 */
export const generateWeatherReportPDF = (reportData: {
  city: string
  temperature: number
  description: string
  humidity: number
  windSpeed: number
  aqi?: number
  forecast?: Array<{ date: string; min: number; max: number }>
}): void => {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Title
  pdf.setFontSize(24)
  pdf.setTextColor(56, 189, 248)
  pdf.text('WeatherCast AI — Weather Report', 20, 25)

  // City and date
  pdf.setFontSize(14)
  pdf.setTextColor(226, 232, 240)
  pdf.text(`City: ${reportData.city}`, 20, 40)
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 50)

  // Weather details
  pdf.setFontSize(12)
  pdf.text(`Temperature: ${Math.round(reportData.temperature)}°C`, 20, 65)
  pdf.text(`Condition: ${reportData.description}`, 20, 75)
  pdf.text(`Humidity: ${reportData.humidity}%`, 20, 85)
  pdf.text(`Wind Speed: ${reportData.windSpeed} m/s`, 20, 95)
  if (reportData.aqi) pdf.text(`AQI: ${reportData.aqi}`, 20, 105)

  // Forecast table
  if (reportData.forecast?.length) {
    pdf.setFontSize(14)
    pdf.text('7-Day Forecast', 20, 125)
    reportData.forecast.forEach((day, i) => {
      pdf.setFontSize(11)
      pdf.text(`${day.date}: ${Math.round(day.min)}° / ${Math.round(day.max)}°`, 20, 140 + i * 10)
    })
  }

  // Footer
  pdf.setFontSize(9)
  pdf.setTextColor(100, 116, 139)
  pdf.text('Generated by WeatherCast AI — ai.weathercast.app', 20, 285)

  pdf.save(`weathercast-${reportData.city.toLowerCase()}-report.pdf`)
}
