// ─────────────────────────────────────────────────────────────
// Nodemailer Email Client — Gmail SMTP
//
// SETUP:
//   1. Gmail → Account → Security → App passwords
//      → Generate 16-char app password
//   2. Add EMAIL_USER, EMAIL_PASS to .env
// ─────────────────────────────────────────────────────────────

import nodemailer from 'nodemailer'

export const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST ?? 'smtp.gmail.com',
  port: Number(process.env.EMAIL_PORT ?? 587),
  secure: false,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
})

/**
 * Send a weather alert email
 */
export const sendAlertEmail = async (params: {
  to: string
  city: string
  alertType: string
  severity: string
  message: string
}): Promise<void> => {
  await transporter.sendMail({
    from: `"WeatherCast AI" <${process.env.EMAIL_USER}>`,
    to: params.to,
    subject: `⚠️ ${params.severity} ${params.alertType} Alert — ${params.city}`,
    html: `
      <div style="font-family: Inter, sans-serif; max-width: 600px; margin: 0 auto; background: #0a0f1e; color: #e2e8f0; padding: 32px; border-radius: 16px;">
        <h1 style="color: #38bdf8; font-size: 24px; margin-bottom: 8px;">WeatherCast AI Alert</h1>
        <p style="color: #94a3b8; margin-bottom: 24px;">Real-time weather intelligence</p>
        <div style="background: rgba(248,113,113,0.1); border: 1px solid rgba(248,113,113,0.3); border-radius: 12px; padding: 20px; margin-bottom: 24px;">
          <h2 style="color: #f87171; margin: 0 0 8px;">🚨 ${params.severity} ${params.alertType.toUpperCase()} ALERT</h2>
          <p style="color: #94a3b8; margin: 0;"><strong style="color: #e2e8f0;">City:</strong> ${params.city}</p>
          <p style="color: #94a3b8; margin-top: 8px;">${params.message}</p>
        </div>
        <p style="color: #64748b; font-size: 12px;">This alert was generated by WeatherCast AI. Stay safe.</p>
      </div>
    `,
  })
}
